#!/bin/bash

usage() {
cat <<EOF
battery: usage:

  general:
    -h, --help    print this message
    -t            output tmux status bar format
    -p            use pmset (more accurate)

  colors:
    -g <color>    good battery level      default: green or 1;32
    -m <color>    middle battery level    default: yellow or 1;33
    -w <color>    warn battery level      default: red or 0;31
EOF
}

if [[ $1 == '-h' || $1 == '--help' || $1 == '-?' ]]; then
  usage
  exit 0
fi

# For default behavior
setDefaults() {
  pmset_on=0
  output_tmux=0
  good_color="1;32"
  middle_color="1;33"
  warn_color="0;31"
  connected=0
}

setDefaults

battery_info() {
    ioreg -c AppleSmartBattery -w0 | \
    grep -o '"[^"]*" = [^ ]*' | \
    sed -e 's/= //g' -e 's/"//g' | \
    sort
}

battery_charge() {
    battery_info | \
    while read key value; do
        case $key in
            "MaxCapacity")
                export maxcap=$value;;
            "CurrentCapacity")
                export curcap=$value;;
        esac
        if [[ -n "$maxcap" && -n $curcap ]]; then
            CAPACITY=$(( 100 * curcap / maxcap))
            printf "%d" $CAPACITY
            break
        fi
    done
}

battery_external_connected() {
  battery_info | grep "ExternalConnected" | cut -f2 -d' '
}

if [[ ! $(battery_external_connected) = "No" ]]; then
  connected=1
fi

# Read args
while getopts ":g:m:w:tph" opt; do
  case $opt in
    g)
      good_color=$OPTARG
      ;;
    m)
      middle_color=$OPTARG
      ;;
    w)
      warn_color=$OPTARG
      ;;
    t)
      output_tmux=1
      good_color="green"
      middle_color="yellow"
      warn_color="red"
      ;;
    p)
      pmset_on=1
      ;;
    \?)
      echo "Invalid option: -$OPTARG"
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument"
      exit 1
      ;;
  esac
done

# Run Battery
if ((pmset_on)); then
  BATTERY_STATUS="$(pmset -g batt | grep -o '[0-9]*%' | tr -d %)"
else
  BATTERY_STATUS="$(battery_charge)"
fi

[[ -z "$BATTERY_STATUS" ]] && exit 1


# Apply the correct color to the battery status prompt
# Green
if [[ $BATTERY_STATUS -ge 75 ]]; then
  if ((output_tmux)); then
    COLOR="#[fg=$good_color]"
  else
    COLOR=$good_color
  fi

# Yellow
elif [[ $BATTERY_STATUS -ge 25 ]] && [[ $BATTERY_STATUS -lt 75 ]]; then
  if ((output_tmux)); then
    COLOR="#[fg=$middle_color]"
  else
    COLOR=$middle_color
  fi

# Red
elif [[ $BATTERY_STATUS -lt 25 ]]; then
  if ((output_tmux)); then
    COLOR="#[fg=$warn_color]"
  else
    COLOR=$warn_color
  fi
fi


# Print the battery status
if ((connected)); then
  GRAPH="⚡"
else
  GRAPH=$(spark 0 ${BATTERY_STATUS} 100 | awk '{print substr($0,4,3)}')
fi

if ((output_tmux)); then
    printf "%s%s %s%s" "$COLOR" "[$BATTERY_STATUS%]" "$GRAPH" "#[default]"
  else
    printf "\e[0;%sm%s %s \e[m\n"  "$COLOR" "[$BATTERY_STATUS%]"  "$GRAPH"
fi
